version: "3.8"

services:
  db:
    build: ./backend/db # <--- CHANGED: Build from our custom file
    container_name: neptune_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: neptune_shipments
    ports:
      - "5455:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: neptune_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@neptune.com
      PGADMIN_DEFAULT_PASSWORD: password123
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data:
